### ISSUE TITLE
Consider Renaming Repository

### ISSUE THREAD

**Issue by DavidBerdik** [chrisdperumal/HideMyVPN#16]
It seems that the planned name for this module is HideMyVPN. I would therefore suggest changing the repository name from `xposed-module-vpn` to `HideMyVPN` to reflect the chosen name.

Since this project belongs to Chris, he has the final say in this, and if he agrees, he must perform the rename.

**Comment by chrisdperumal** [comment]
Good idea. I've renamed it

**Comment by DavidBerdik** [comment]
Thank you! 😁
